posts-per-page: 10
tagsUrls:
  题目: /category/prob/
  BZOJ: /category/bzoj/
  Codeforces: /category/cf/
  算法: /category/algo/
  高精度: /category/gjd/
  字符串: /category/str/
  kmp: /category/kmp/
  回文自动机: /category/hwz/
  SAM: /category/sam/
  乱搞: /category/hhh/
  找规律: /category/zgl/
  暴力: /category/cqj/
  DP: /category/dp/
  矩阵快速幂: /category/jzk/
  状压dp: /category/zy/
  背包dp: /category/pk/
  数论: /category/math/
  扩展gcd: /category/exgcd/
  lucas定理: /category/luc/
  burnside引理: /category/bsd/
  莫比乌斯反演: /category/mob/
  图论: /category/gr/
  最短路: /category/zd/
  网络流: /category/nfl/
  最大流: /category/mfl/
  分治: /category/fz/
  二分答案: /category/eas/
  CDQ分治: /category/cdq/
  分块: /category/fk/
  倍增: /category/bz/
  LCA: /category/lca/
  贪心: /category/tx/
  FFT: /category/FFT/
  并查集: /category/uf/
  数据结构: /category/ds/
  线段树: /category/seg/
  LCT: /category/lct/
  树套树: /category/sts/
  树状数组: /category/sz/
  点分治: /category/df/
  kdtree: /category/kd/
  杂项: /category/emmmmm/
  回忆录: /category/remmmmm/
  CTF: /category/ctf/
  Writeup: /category/wp/
requireFiles:
  - /assets/style.css
